### ISSUE TITLE
z values in netfacs()

### ISSUE THREAD

**Issue by gobbios** [AlexMielke1988/NetFACS#10]
I'm not really convinced that setting _z_ to 10 is appropriate in cases where the SD = 0. Wouldn't it be more prudent to return such cases as `NA`?

**Comment by AlexMielke1988** [comment]
NA would potentially create problems down the line and might hide the most relevant elements (those that differ entirely between contexts). Don't know a good solution for this.

**Comment by AlexMielke1988** [comment]
have now adapted all functions to work even if the z value is NA
