### ISSUE TITLE
comb_names not created

### ISSUE THREAD

**Issue by AlexMielke1988** [AlexMielke1988/NetFACS#14]
when I download the package straight from GitHub, some of the Rcpp functions (especially comb_names) are not created. They are also not on the GitHub. I can't use the package because of that

**Comment by AlexMielke1988** [comment]
I have set the standard in the netfacs function to use_cpp = F for now; I do not know where the comb_names has gotten to

**Comment by gobbios** [comment]
Is it possible you work on a fork or branch? The functions in should be there:

https://github.com/AlexMielke1988/NetFACS/blob/master/src/combi_props.cpp

**Comment by gobbios** [comment]
Just tried:

`devtools::install_github("AlexMielke1988/NetFACS")`

which works fine and provides:
`NetFACS:::comb_names`

**Comment by AlexMielke1988** [comment]
Have you tried it with the parLapply? Because on my computer, the clusterExport does not catch it. 

mycluster <- makeCluster(spec = n_cores, type = "PSOCK")
>         # export the relevant information to each core
>         clusterExport(cl = mycluster,
+                       c("ran.trials",
+                         "elements.null",
+                         "max.event.size",
+                         "rs.test",
+                         "condition.x",
+                         "rl.null.ratio",
+                         "combination.size",
+                         "random.level.null",
+                         "rules_foo"),
+                       envir = environment())
>         registerDoParallel(mycluster)
>         # run parallel loop
>         boot.values <- parLapply(cl = mycluster,
+                                  X = 1:ran.trials,
+                                  fun = boot_foo)
Error in checkForRemoteErrors(val) : 
  3 nodes produced errors; first error: object 'comb_names' not found
Called from: checkForRemoteErrors(val)

**Comment by AlexMielke1988** [comment]
And if I add 'comb_names', it still tells me:

Error in checkForRemoteErrors(val) : 
  3 nodes produced errors; first error: NULL value passed as symbol address
Called from: checkForRemoteErrors(val)

So there is still something missing in the clusterExport, but I can't tell what it is

**Comment by gobbios** [comment]
Just tried, and it works fine for me. And you wouldn't need to add `comb_names` to that list (it's just a utility function, which should be covered by `rules_foo`). So, I don't think the cluster is the problem here. Did you try (to pull the repo and) reinstall? To me this looks like your package installation got messed up somehow. What do you get if you do this:

```
library(NetFACS)
NetFACS:::comb_names
```

If that results in some kind of error or warning that would support my guess. If it works you should get:
```
function (elements, comb) 
{
    .Call("_NetFACS_comb_names", PACKAGE = "NetFACS", elements, 
        comb)
}
<bytecode: 0x7feb1a44ce00>
<environment: namespace:NetFACS>
```

**Comment by AlexMielke1988** [comment]
I get
function(elements, comb) {
    .Call('_NetFACS_comb_names', PACKAGE = 'NetFACS', elements, comb)
}
<environment: namespace:NetFACS>

**Comment by AlexMielke1988** [comment]
actually this might be the problem, it only exists in the NetFACS environment, while the parLapply calls 'envir = environment()'

**Comment by gobbios** [comment]
Oh, you are working interactively *inside* the function? I thought you tried the function after reinstalling. My bad. So yes, you might need to set

```
  if (use_cpp) {
    rules_foo <- NetFACS:::create_rule_set2
    shuffle_foo_1 <- NetFACS:::shuffle_rowwise
    shuffle_foo_2 <- NetFACS:::shuffle_checkerboard
  }
```

at the top of the function definition. I removed the explicit `NetFACS:::` because R CMD check complains about it. (and it should work once the package is compiled and 'packaged')

**Comment by AlexMielke1988** [comment]
OK, this seems to solve the issue. I think there are generally some issue with compiling it when I download and when I use 'check', it seems somehow unhappy with Rcpp_armadillo. I'll try to redo everything now that the netfacs function seems to work to see if the compilation errors persist

**Comment by gobbios** [comment]
What I mean is, just add the `NetFACS:::` to these lines and we leave them there until before submission to CRAN.
Alternatively, I could just export the functions, despite them being pretty useless in the context of the package.

**Comment by gobbios** [comment]
Great. If you get complaints from `devtools::check()` just let me know. As I said, for me there are now only two warnings (compression and the `:::`).

**Comment by AlexMielke1988** [comment]
Check() does not pass any of the examples on my computer if use_cpp = TRUE or use_parallel = TRUE, and it constantly finds fault with the example of 'create_rule_set2' . These pass if I use devtools::run_examples(), so I think they are fine in general, but there is a problem with the use of the compiled functions.
