### ISSUE TITLE
network.conditional

### ISSUE THREAD

**Issue by gobbios** [AlexMielke1988/NetFACS#17]
Here is a bit of code to replace the non-graphical part of `network.conditional`. It's less code and is a little bit faster than what is there at the moment, and it doesn't require `arules`. I didn't include it myself because I'm uncertain about which data exactly should be used for it: the `arules` object included in the output of `netfacs` seems to reflect only the 'test elements', whereas I would think that either it should be done on all events, or at least allow the user to specify the 'test condition'? At the least I think, the documentation for `network.conditional` should state whatever is the case.

```
conditional_foo <- function(indata) {
  # indata is the raw data matrix (either all events or only test condition)
  # pairs of units
  xpairs <- combn(colnames(indata), 2)
  # PA and PB
  pa_and_pb <- apply(xpairs, 2, function(x) colSums(indata[, x])) / nrow(indata)
  # PAB
  pab <- apply(xpairs, 2, function(x) sum(rowSums(indata[, x]) == 2)) / nrow(indata)
  # PA|B
  pa_b <- apply(xpairs, 2, function(x) sum(rowSums(indata[, x]) == 2) / sum(indata[, x[2]]))
  # PB|A
  pb_a <- apply(xpairs, 2, function(x) sum(rowSums(indata[, x]) == 2) / sum(indata[, x[1]]))
  
  # put together
  out <- data.frame(elementA = as.character(xpairs), 
                    elementB = as.character(xpairs[2:1, ]))
  out$combination <- rep(apply(xpairs, 2, paste, collapse = "_"), each = 2)
  out$count <- rep(pab * nrow(indata), each = 2)
  out$`P(A)` <- as.numeric(pa_and_pb)
  out$`P(B)` <- as.numeric(pa_and_pb[2:1, ])
  out$`P(A+B)` <- rep(pab, each = 2)
  out$`P(A|B)` <- as.numeric(rbind(pa_b, pb_a))

  out <- out[out$count > 0,]
  out[order(out$count), ]
}
```

And one more point, it's not 'good style' to have column names that require backticks. It shouldn't be a big thing to change those column names to something 'safe' and meaningful.

**Comment by AlexMielke1988** [comment]
Changed the script and changed the column names.
